### ISSUE TITLE
您好，发现一个小问题。

### ISSUE THREAD

**Issue by EngineeringSample** [spiritLHLS/lxc#10]
我发现每一次开小鸡，开到100的时候，就不能再往下开了，是什么原因呢？每一次都是正好100。好奇。。。

**Comment by EngineeringSample** [comment]
下面是具体报错
Creating ex103
Device root overridden for ex103
Device eth0 overridden for ex103
Err:1 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Err:1 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ca-certificates libbrotli1 libcurl4 libldap-2.4-2 libldap-common libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libssh2-1 openssl publicsuffix
Suggested packages:
  libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql
The following NEW packages will be installed:
  ca-certificates curl dos2unix libbrotli1 libcurl4 libldap-2.4-2 libldap-common libnghttp2-14 libpsl5 librtmp1 libsasl2-2
  libsasl2-modules libsasl2-modules-db libssh2-1 openssl publicsuffix
0 upgraded, 16 newly installed, 0 to remove and 0 not upgraded.
Need to get 3385 kB of archives.
After this operation, 7608 kB of additional disk space will be used.
Err:1 http://deb.debian.org/debian-security bullseye-security/main amd64 openssl amd64 1.1.1n-0+deb11u5
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian bullseye/main amd64 ca-certificates all 20210119
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian bullseye/main amd64 libbrotli1 amd64 1.0.9-2+b2
  Temporary failure resolving 'deb.debian.org'
Ign:4 http://deb.debian.org/debian bullseye/main amd64 libsasl2-modules-db amd64 2.1.27+dfsg-2.1+deb11u1
Ign:5 http://deb.debian.org/debian bullseye/main amd64 libsasl2-2 amd64 2.1.27+dfsg-2.1+deb11u1
Ign:6 http://deb.debian.org/debian bullseye/main amd64 libldap-2.4-2 amd64 2.4.57+dfsg-3+deb11u1
Err:7 http://deb.debian.org/debian bullseye/main amd64 libnghttp2-14 amd64 1.43.0-1
  Temporary failure resolving 'deb.debian.org'
Err:8 http://deb.debian.org/debian bullseye/main amd64 libpsl5 amd64 0.21.0-1.2
  Temporary failure resolving 'deb.debian.org'
Err:9 http://deb.debian.org/debian bullseye/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2+b2
  Temporary failure resolving 'deb.debian.org'
Err:10 http://deb.debian.org/debian bullseye/main amd64 libssh2-1 amd64 1.9.0-2
  Temporary failure resolving 'deb.debian.org'
Ign:11 http://deb.debian.org/debian bullseye/main amd64 libcurl4 amd64 7.74.0-1.3+deb11u7
Ign:12 http://deb.debian.org/debian bullseye/main amd64 curl amd64 7.74.0-1.3+deb11u7
Err:13 http://deb.debian.org/debian bullseye/main amd64 dos2unix amd64 7.4.1-1
  Temporary failure resolving 'deb.debian.org'
Ign:14 http://deb.debian.org/debian bullseye/main amd64 libldap-common all 2.4.57+dfsg-3+deb11u1
Ign:15 http://deb.debian.org/debian bullseye/main amd64 libsasl2-modules amd64 2.1.27+dfsg-2.1+deb11u1
Err:16 http://deb.debian.org/debian bullseye/main amd64 publicsuffix all 20220811.1734-0+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:4 http://deb.debian.org/debian bullseye/main amd64 libsasl2-modules-db amd64 2.1.27+dfsg-2.1+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:5 http://deb.debian.org/debian bullseye/main amd64 libsasl2-2 amd64 2.1.27+dfsg-2.1+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:6 http://deb.debian.org/debian bullseye/main amd64 libldap-2.4-2 amd64 2.4.57+dfsg-3+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:11 http://deb.debian.org/debian bullseye/main amd64 libcurl4 amd64 7.74.0-1.3+deb11u7
  Temporary failure resolving 'deb.debian.org'
Err:12 http://deb.debian.org/debian bullseye/main amd64 curl amd64 7.74.0-1.3+deb11u7
  Temporary failure resolving 'deb.debian.org'
Err:14 http://deb.debian.org/debian bullseye/main amd64 libldap-common all 2.4.57+dfsg-3+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:15 http://deb.debian.org/debian bullseye/main amd64 libsasl2-modules amd64 2.1.27+dfsg-2.1+deb11u1
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/o/openssl/openssl_1.1.1n-0%2bdeb11u5_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/ca-certificates/ca-certificates_20210119_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/b/brotli/libbrotli1_1.0.9-2%2bb2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/c/cyrus-sasl2/libsasl2-modules-db_2.1.27%2bdfsg-2.1%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/c/cyrus-sasl2/libsasl2-2_2.1.27%2bdfsg-2.1%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/o/openldap/libldap-2.4-2_2.4.57%2bdfsg-3%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/n/nghttp2/libnghttp2-14_1.43.0-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/libp/libpsl/libpsl5_0.21.0-1.2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/r/rtmpdump/librtmp1_2.4%2b20151223.gitfa8646d.1-2%2bb2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/libs/libssh2/libssh2-1_1.9.0-2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/c/curl/libcurl4_7.74.0-1.3%2bdeb11u7_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/c/curl/curl_7.74.0-1.3%2bdeb11u7_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/d/dos2unix/dos2unix_7.4.1-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/o/openldap/libldap-common_2.4.57%2bdfsg-3%2bdeb11u1_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/c/cyrus-sasl2/libsasl2-modules_2.1.27%2bdfsg-2.1%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/publicsuffix/publicsuffix_20220811.1734-0%2bdeb11u1_all.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Command not found                                                   
sed: can't read /etc/sysconfig/selinux: No such file or directory
sed: can't read /etc/selinux/config: No such file or directory
sudo: setenforce: command not found
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  sshpass
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.0 kB of archives.
After this operation, 38.9 kB of additional disk space will be used.
Err:1 http://deb.debian.org/debian bullseye/main amd64 sshpass amd64 1.09-1+b1
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/sshpass/sshpass_1.09-1%2bb1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libwrap0 ncurses-term openssh-sftp-server runit-helper sensible-utils ucf
Suggested packages:
  molly-guard monkeysphere ssh-askpass ufw
The following NEW packages will be installed:
  libwrap0 ncurses-term openssh-server openssh-sftp-server runit-helper sensible-utils ucf
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 1098 kB of archives.
After this operation, 6447 kB of additional disk space will be used.
Err:1 http://deb.debian.org/debian bullseye/main amd64 sensible-utils all 0.0.14
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian bullseye/main amd64 ncurses-term all 6.2+20201114-2+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian bullseye/main amd64 ucf all 3.0043
  Temporary failure resolving 'deb.debian.org'
Err:4 http://deb.debian.org/debian bullseye/main amd64 libwrap0 amd64 7.6.q-31
  Temporary failure resolving 'deb.debian.org'
Err:5 http://deb.debian.org/debian bullseye/main amd64 openssh-sftp-server amd64 1:8.4p1-5+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:6 http://deb.debian.org/debian bullseye/main amd64 runit-helper all 2.10.3
  Temporary failure resolving 'deb.debian.org'
Err:7 http://deb.debian.org/debian bullseye/main amd64 openssh-server amd64 1:8.4p1-5+deb11u1
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/sensible-utils/sensible-utils_0.0.14_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/n/ncurses/ncurses-term_6.2%2b20201114-2%2bdeb11u1_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/u/ucf/ucf_3.0043_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/t/tcp-wrappers/libwrap0_7.6.q-31_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/o/openssh/openssh-sftp-server_8.4p1-5%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/d/dh-runit/runit-helper_2.10.3_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/o/openssh/openssh-server_8.4p1-5%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
sed: can't read /etc/ssh/sshd_config: No such file or directory
sed: can't read /etc/ssh/sshd_config: No such file or directory
sed: can't read /etc/ssh/sshd_config: No such file or directory
sed: can't read /etc/ssh/sshd_config: No such file or directory
sed: can't read /etc/ssh/sshd_config: No such file or directory
sed: can't read /etc/ssh/sshd_config: No such file or directory
Failed to restart ssh.service: Unit ssh.service not found.
Failed to restart sshd.service: Unit sshd.service not found.
Package: zmap nmap masscan medusa apache2-utils hping3                             
Pin: release *
Pin-Priority: -1
Err:1 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Error: Command not found
Device ssh-port added to ex103
Device nattcp-ports added to ex103
Device natudp-ports added to ex103
ex103 20103 de47a91cb 32653 32678
Creating ex104
Device root overridden for ex104
Device eth0 overridden for ex104
Error: Instance is not running 
Error: Instance is not running
Error: Instance is not running
Error: Instance is not running
Error: Instance is not running                                             
Error: Instance is not running
Error: Instance is not running
Error: Instance is not running                                                   
Error: Instance is not running
Error: Instance is not running
Device ssh-port added to ex104
Device nattcp-ports added to ex104
Device natudp-ports added to ex104
ex104 20104 80bd830a4 32679 32704

**Comment by spiritLHLS** [comment]
100个?

好家伙，我没考虑过这么多容器的情况，我暂时没有头绪，明天我看看

刚刚修复了部分可能存在的依赖问题，有空你可以更新脚本再试试，也许问题会得到解决

**Comment by EngineeringSample** [comment]
好的，感谢。我试试

**Comment by EngineeringSample** [comment]
您好，并没有什么用处

**Comment by spiritLHLS** [comment]
近期有点忙，下周我找个时间看看

目前如果依赖没问题，那应该就是端口映射那块有冲突，或者什么设置有毛病，导致后续开启容器失败

**Comment by EngineeringSample** [comment]
好的，谢谢您。

**Comment by spiritLHLS** [comment]
已修复，LXD的一键安装脚本增加进程数限制解除部分的内容，DNS增加各种补丁，保证小鸡依赖不出现一堆Err了
