### ISSUE TITLE
机子开不出来小鸡 报错 不知道什么意思

### ISSUE THREAD

**Issue by huashu2021** [spiritLHLS/lxc#11]
Error: Failed to handle idmapped storage: Failed to change ownership of: /var/snap/lxd/common/lxd/storage-pools/default/containers/ex2/rootfs/usr/lib/terminfo/w/wsvt25m

**Comment by spiritLHLS** [comment]
脚本更新了，再试试新脚本

**Comment by huashu2021** [comment]
还是不行 报错还是这个

Creating ex1
Device root overridden for ex1                
Device eth0 overridden for ex1
Error: Failed to handle idmapped storage: Failed to change ownership of: /var/snap/lxd/common/lxd/storage-pools/default/containers/ex1/rootfs/usr/share/doc/libkrb5-3
Try `lxc info --show-log ex1` for more info
Error: Instance is not running
Error: Instance is not running
Error: Instance is not running

**Comment by huashu2021** [comment]
我看了一下 这个实际的路径就到了/var/snap/lxd/common/lxd/storage-pools/default 后面没有东西了

**Comment by spiritLHLS** [comment]
本机好像虚拟化不支持？
你这台机器是什么虚拟化的?

**Comment by huashu2021** [comment]
Virtualization: VT-x
Hypervisor vendor:  KVM
Virtualization type: full

**Comment by huashu2021** [comment]
可能是系统问题，装了个Ubuntu没问题了

**Comment by spiritLHLS** [comment]
推荐Ubuntu，Debian部分模板奇葩我不知道会出现什么奇奇怪怪的BUG
