### ISSUE TITLE
缺少镜像系统

### ISSUE THREAD

**Issue by soeceo** [spiritLHLS/lxc#12]
如果率先支持centos6.x和centos7.x就最好了

**Comment by spiritLHLS** [comment]
LXD基于Ubuntu开发，暂时没捣鼓过centos系的，如果有snap命令那应该大差不差也能用，手动命令自己改改吧

**Comment by soeceo** [comment]
lxdpro.sh那个就有centos7.x，因为毕竟有很多软件仅支持centos系，但是他那个端口转发根本就无法加入，等于说只能生产小鸡无法使用，你这个一键就很好用，一键开通小鸡加端口即可使用

**Comment by spiritLHLS** [comment]
已添加多系统支持
