### ISSUE TITLE
一个关于ipv6的问题-Ubuntu22

### ISSUE THREAD

**Issue by EngineeringSample** [spiritLHLS/lxc#13]
我发现使用脚本配置ipv6时一切正常，当重启后，ipv6无法使用，nat-ipv4仍然正常。
我发现问题的系统：乌班图22

**Comment by spiritLHLS** [comment]
ubuntu22没有测试过，ubuntu20我记得测试的没问题，ubuntu22有空我看看什么情况吧，目前建议使用ubuntu20看看

**Comment by spiritLHLS** [comment]
应该是机器没持久化保存绑定的IPV6地址，/etc/network/interfaces没有保存地址，晚些时候我修复一下

**Comment by spiritLHLS** [comment]
已修复，增加守护进程处理该问题
