### ISSUE TITLE
提一些关于LXC小问题

### ISSUE THREAD

**Issue by EngineeringSample** [spiritLHLS/lxc#14]
现在的批量脚本不能设置硬盘，内存，cpu，网速，系统等信息了吗？
LXC的系统有alpine吗？

**Comment by spiritLHLS** [comment]
https://virt.spiritlhl.net/guide/lxd_lxc.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%89%88%E6%9C%AC%E6%89%B9%E9%87%8F%E7%94%9F%E6%88%90

暂无alpine

**Comment by EngineeringSample** [comment]
您好，现在的一些问题

匹配的镜像存在
./buildone.sh: line 38: jq: command not found
匹配的镜像存在，将使用 images: 进行创建
Creating ex1
Error: Failed instance creation: Failed getting image: The requested image couldn't be found
容器创建失败，请检查前面的输出信息
cat: ex1: No such file or directory
./buildone.sh: line 38: jq: command not found
匹配的镜像存在，将使用 images: 进行创建
Creating ex2
Error: Failed instance creation: Failed getting image: The requested image couldn't be found
容器创建失败，请检查前面的输出信息
cat: ex2: No such file or directory
./buildone.sh: line 38: jq: command not found
匹配的镜像存在，将使用 images: 进行创建
Creating ex3
Error: Failed instance creation: Failed getting image: The requested image couldn't be found
容器创建失败，请检查前面的输出信息
cat: ex3: No such file or directory
./buildone.sh: line 38: jq: command not found
匹配的镜像存在，将使用 images: 进行创建
Creating ex4
Error: Failed instance creation: Failed getting image: The requested image couldn't be found
容器创建失败，请检查前面的输出信息
cat: ex4: No such file or directory
./buildone.sh: line 38: jq: command not found

**Comment by EngineeringSample** [comment]
用普通版本批量生成没问题

**Comment by spiritLHLS** [comment]
./buildone.sh 只能在使用了LXD一键安装命令安装的，如果不是的话需要安装jq命令，我补上吧

**Comment by EngineeringSample** [comment]
好的，谢谢了

**Comment by EngineeringSample** [comment]
我记得之前安装LXD之后，就可以直接使用批量脚本

**Comment by spiritLHLS** [comment]
> 我记得之前安装LXD之后，就可以直接使用批量脚本

最近更换了组件的检测方式，所以漏了某些组件，现在改回来了应该没毛病了

**Comment by EngineeringSample** [comment]
期待对alpine的支持
