### ISSUE TITLE
关于alpine的支持

### ISSUE THREAD

**Issue by EngineeringSample** [spiritLHLS/lxc#15]
请问''自定义版本批量生成''什么时候支持alpine？我目前貌似无法使用
问题如下：
每个小鸡的系统是什么？(注意传入参数为系统名字+版本号，如：debian11、ubuntu20、centos7)：alpine3.16
匹配的镜像存在
未找到匹配的镜像，请执行
lxc image list images:系统/版本号
查询是否存在对应镜像
cat: ex1: No such file or directory

**Comment by spiritLHLS** [comment]
已更新支持输入alpine系统，说明文档已更新
