### ISSUE TITLE
您好，提一个有关ipv6小建议

### ISSUE THREAD

**Issue by EngineeringSample** [spiritLHLS/lxc#16]
您好，我发现在LXC中对ipv6的分配，貌似只可以默认网卡的ipv6 /64
我希望可以添加更多的可自定义，比如自定义网卡（比如说默认是eth0，但我ipv6在eth1上面）
和自定义ipv6类型，比如说支持/48的支持，及其他的支持（不只局限于/64)
希望可以采纳。

**Comment by spiritLHLS** [comment]
有空再适配了

**Comment by EngineeringSample** [comment]
好的，谢谢

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/lxc/commit/ab3fa03939943ba4d0ed50bf717229e544fc54e9

应该适配了，但未测试，明天测试
