### ISSUE TITLE
貌似有点问题，ssh没有开启

### ISSUE THREAD

**Issue by moeik** [spiritLHLS/lxc#17]
如图，找不到指定文件，请问是什么情况呢？
Debian11宿主机ovh

![image](https://github.com/spiritLHLS/lxc/assets/49871008/52310560-b5b1-43e7-8ab3-6c00e91b08ed)

**Comment by spiritLHLS** [comment]
宿主机的 /root 路径下是否有对应 ssh.sh config.sh 文件？
你是手动安装还是一键安装的lxd主体？
如果是一键安装默认会加载对应文件，如果是手动安装，那么需要对应下载文件

**Comment by spiritLHLS** [comment]
近期应酬，9号晚上才有空修复可能存在的问题，有事留言，不一定及时回复

**Comment by moeik** [comment]
> 

了解 我试试一键安装 谢谢

**Comment by moeik** [comment]
> 宿主机的 /root 路径下是否有对应 ssh.sh config.sh 文件？ 你是手动安装还是一键安装的lxd主体？ 如果是一键安装默认会加载对应文件，如果是手动安装，那么需要对应下载文件

貌似还是有问题。我把script都放进来了 +x权限了也

![image](https://github.com/spiritLHLS/lxc/assets/49871008/fd800b18-3d3f-4966-8bc8-a2895ae7a6c5)
![image](https://github.com/spiritLHLS/lxc/assets/49871008/0da9db8d-a235-43ef-991b-1ed057255fb7)

**Comment by moeik** [comment]
噢 好像所有脚本都必须放在/root目录下对吧。。。

**Comment by spiritLHLS** [comment]
是的，路径是宿主机的 /root，也就是执行sudo -i后的地方
因为暂时没写别的地方放，有空我改改不强制要求/root吧
开发环境是Ubuntu20，如果debian还有问题切换为这个环境应该是没问题的

**Comment by moeik** [comment]
> 是的，路径是宿主机的 /root，也就是执行sudo -i后的地方 因为暂时没写别的地方放，有空我改改不强制要求/root吧 开发环境是Ubuntu20，如果debian还有问题切换为这个环境应该是没问题的

我回来了，重新试了很多次，一键安装脚本可以完成安装，但/root目录下没有相应的脚本如ssh.sh 导致新建小鸡也是失败，另外好像一件安装脚本安装得不完整，上方/snap/bin/lxd init这块内容没有执行，手动下载开机脚本 开小鸡报错 ，重新执行/snap/bin/lxd init之后才能正常开机，同样没有映射ipv4端口

主机商ovh 杜甫
debian11

**Comment by spiritLHLS** [comment]
尝试修复了一下，你可以再试试

我目前在我的debian11和Ubuntu20上测试的没问题了
