### ISSUE TITLE
手动安装怎么增加小鸡的磁盘

### ISSUE THREAD

**Issue by alonedogboy** [spiritLHLS/lxc#2]
默认1G的空间，怎么增加呢

**Comment by alonedogboy** [comment]
还有限速怎么改，求大佬指点

**Comment by spiritLHLS** [comment]
磁盘自定义的话，最后那个一键脚本有自定义，限速我没设置可变，后续我再改成可变的限速吧

https://github.com/spiritLHLS/lxc/blob/main/buildone.sh

脚本有注释，你可以下载后自己更改里面的内容再使用

如果你是手动安装的

https://github.com/spiritLHLS/lxc/blob/main/init.sh

https://github.com/spiritLHLS/lxc/blob/main/least.sh

注释部分内容是相同的，可以对照着改完再使用脚本

**Comment by spiritLHLS** [comment]
最后那个一键脚本的自定义已更新支持网速自定义
