### ISSUE TITLE
问一个关于网络的问题

### ISSUE THREAD

**Issue by QASDJKL5** [spiritLHLS/lxc#23]
母鸡是甲骨文arm，系统是dd过的Ubuntu20.04，用自动lxd安装后开小鸡就会导致母鸡无法解析dns，请问是哪里出问题了

**Comment by spiritLHLS** [comment]
是不是安装后未重启系统就去开小鸡了？dns自动补全的服务未真正启动可能导致该问题，开设lxd小鸡时可能会重置宿主机的dns 此时若没有补全锁死文件，就会出现你说的问题

**Comment by QASDJKL5** [comment]
谢谢解答，装完看到提示了，怪我之前看的不清楚
