### ISSUE TITLE
开通的小鸡进行DD切换系统后22端口是关闭的

### ISSUE THREAD

**Issue by soeceo** [spiritLHLS/lxc#24]
请检查一下，小鸡是centos7,openssh 也安装过了，iptables也安装过了，默认含22，也restart了network，也reboot过了

**Comment by spiritLHLS** [comment]
是不是没更新脚本？我本人测试开设没问题
如果有问题请截图展示开设过程中的日志

**Comment by spiritLHLS** [comment]
唯一有可能有问题的地方今天我也加入修复了

https://github.com/spiritLHLS/lxd/commit/3c097601d59b6174db2ffb79c4ae848bd94ca0be

务必使用一键更新命令

https://virt.spiritlhl.net/guide/lxd_lxc.html#%E6%9B%B4%E6%96%B0%E4%B8%8A%E8%BF%B0%E6%89%80%E6%9C%89%E4%B8%80%E9%94%AE%E8%84%9A%E6%9C%AC%E7%9A%84%E7%9B%B8%E5%85%B3%E5%91%BD%E4%BB%A4

更新全部脚本后再次尝试

**Comment by soeceo** [comment]
找到原因了
如果是自行dd系统的，并在代码中直接加入指定ssh端口，那么22端口最后是关闭的
需要再sshd中再加入Port 22，并重启网卡生效，否则宿主机22端口不开放，开通的小鸡v6对应的22服务也不起作用
加入后还需重启宿主机生效小鸡v6才能连接上

**Comment by spiritLHLS** [comment]
> 找到原因了 如果是自行dd系统的，并在代码中直接加入指定ssh端口，那么22端口最后是关闭的 需要再sshd中再加入Port 22，并重启网卡生效，否则宿主机22端口不开放，开通的小鸡v6对应的22服务也不起作用 加入后还需重启宿主机生效小鸡v6才能连接上

自行DD小鸡的系统这块就不在我考虑范围内了，你需要找对应DD系统脚本的作者做这件事，原生的系统应该是没问题的

**Comment by soeceo** [comment]
另外，发现个新问题，就是小鸡的v6 连接ssh不稳定啊，这相比之前一点都没有之前的v6稳定，每次都要通过exec进入小鸡reboot等一会才能连接上，v4加指定端口没问题

刚刚看了小鸡的eth0配置，发现用的dhcp而不是static，没自动加子网也没有dns。
