### ISSUE TITLE
开通的容器的IPV6的ssh不稳定

### ISSUE THREAD

**Issue by soeceo** [spiritLHLS/lxc#26]
发现个新问题，就是小鸡的v6连接ssh不稳定啊，这相比之前一点都没有之前的v6稳定，每次都要通过exec进入小鸡reboot等一会才能连接上，v4加指定端口没问题

刚刚查看了小鸡的eth0配置，发现用的dhcp不是static的，没有自动加子网也没有dns。

**Comment by spiritLHLS** [comment]
已解决，增加可选的方法进行IPV6的网络映射
