### ISSUE TITLE
LXC虚拟化创建小鸡命令中的网络限速在多线程情况下不起作用

### ISSUE THREAD

**Issue by xinvhost** [spiritLHLS/lxc#27]
创建LXC小鸡的网络限速不起作用
例如：
./buildone.sh test 1 256 2 20001 20002 20025 20 20 N
其中 设置为限制20Mbit的上传带宽和下载带宽不起作用，实际测速并没有限制，重启主机网络和小鸡网络后测试依然没有限速

另外：这个脚本非常的丝滑好用，目前就发现这一个问题，作者大佬牛比

**Comment by xinvhost** [comment]
测试过母鸡为 ubuntu20和debian10，开出的小鸡不管是什么系统，限速都不能很好的起作用，比如搭建一个http服务，从这个http服务下载文件，单线程貌似有时正常限速，但如果多线程下载限速就不起作用了；

PS；我并不明白其中限速的原理是什么，盲猜可能是通过进程限速之类的

建议：我看到一个类似的脚本，他貌似是通过不同小鸡创建不同的NAT网卡对网卡限速的，https://github.com/MXCCO/lxdpro ，这个的限速非常好用，作者也可以考虑参考下这个脚本的思路

**Comment by spiritLHLS** [comment]
![图片](https://github.com/spiritLHLS/lxd/assets/103393591/279f40e8-217b-4096-821d-a047b2eb1c8f)
上面是他的，这是我的，没啥不同，无非是多了一个max的限制，如果是这个有用的话晚点我加上吧
![图片](https://github.com/spiritLHLS/lxd/assets/103393591/47baba77-0529-40c4-a82f-800cfaeca52c)

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/lxd/commit/2d6e0aa29058e89d4b2c7dae7b1d832ab2fd5ec9
