### ISSUE TITLE
下载限速不起作用

### ISSUE THREAD

**Issue by xinvhost** [spiritLHLS/lxc#28]
上次修改后上传限速正常没啥问题了，但下载限速还是不起作用，希望大佬修复，大佬辛苦了
详细：
比如用下面这个命令创建一个lxc容器
./buildone.sh test 1 256 2 20001 20002 20025 **150** **200** N
则前面的上传限速150Mbps是起作用的，测速脚本和http服务测试上传限速都是正常的；
但**下载限速200Mbps不起作用**，**见附图**
![19220658](https://github.com/spiritLHLS/lxd/assets/117034208/5cc7115c-c387-4c72-89e6-d947d62d8d38)

**Comment by spiritLHLS** [comment]
有空我翻翻文档看看

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/lxd/commit/cacf0b7101fcbf568f098c8a24bf20e49ef4adb5

换了一种写法，可能有用了
