### ISSUE TITLE
(找不到版本号) LXD的镜像源可能暂不支持非Ubuntu镜像了，详情见仓库说明

### ISSUE THREAD

**Issue by v2-share** [spiritLHLS/lxc#29]
输入无效，请输入一个存在的系统

**Comment by spiritLHLS** [comment]
缘由：https://t.me/spiritlhl/176

**Comment by spiritLHLS** [comment]
需要等待官方的第三方镜像出来，否则这段时间最好使用

https://github.com/oneclickvirt/incus

**Comment by spiritLHLS** [comment]
https://github.com/oneclickvirt/lxd/commit/f6f01be43a32a229a81ccf7c5177c570c4ff2836

已修复
