### ISSUE TITLE
在甲骨文amd安装后没有ssh

### ISSUE THREAD

**Issue by banbanfan** [spiritLHLS/lxc#30]
在甲骨文amd安装后没有ssh，

![J3{NH5JFF0R{$4~5337CK4A](https://github.com/oneclickvirt/lxd/assets/130959835/96145ffa-f939-4615-a13f-6b8de62ab6bc)

还有，这是怎么分配IPV6的
![AP1UV1JLX%XZ0CYFQ)0O6E8](https://github.com/oneclickvirt/lxd/assets/130959835/aec9a3d8-eec4-4b9e-bcb6-ee5d072751f6)

**Comment by spiritLHLS** [comment]
> 在甲骨文amd安装后没有ssh，
> 
> ![J3{NH5JFF0R{$4~5337CK4A](https://private-user-images.githubusercontent.com/130959835/322845048-96145ffa-f939-4615-a13f-6b8de62ab6bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzIyNTYsIm5iZiI6MTcxMzI3MTk1NiwicGF0aCI6Ii8xMzA5NTk4MzUvMzIyODQ1MDQ4LTk2MTQ1ZmZhLWY5MzktNDYxNS1hMTNmLTZiOGRlNjJhYjZiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMjUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzQ3MmFiNTkxNDZlNWJjODFlNTQ2ZWMxNWViNzQ1NDQyMjQ2NzQwNDQ4ZjE4YjFjMjVkMmNkZmVjOWIyYzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TNIGCJiQ3mtMRs7J2bJLnb743NlnSZuX3kaK9ilqwrk)
> 
> 还有，这是怎么分配IPV6的 ![AP1UV1JLX%XZ0CYFQ)0O6E8](https://private-user-images.githubusercontent.com/130959835/322845860-aec9a3d8-eec4-4b9e-bcb6-ee5d072751f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzIyNTYsIm5iZiI6MTcxMzI3MTk1NiwicGF0aCI6Ii8xMzA5NTk4MzUvMzIyODQ1ODYwLWFlYzlhM2Q4LWVlYzQtNGI5ZS1iY2I2LWVlNWQwNzI3NTFmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMjUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWMzYjg3ZWQyMmVkYTFkN2NlZDAwNTUwNjU3MTJiYmU0NGY2NzhjNzBhMGM2YzFiZTgxNDczMWY4NzQwNjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2xypipMYPE-n_qiNri48DYPNi9sOcSF0dzBN1JUrrgU)

进容器查看```lsof -i:22```
还有，如果是新系统，推荐使用 https://github.com/oneclickvirt/incus

**Comment by banbanfan** [comment]
> > 在甲骨文amd安装后没有ssh，
> > ![J3{NH5JFF0R{$4~5337CK4A](https://private-user-images.githubusercontent.com/130959835/322845048-96145ffa-f939-4615-a13f-6b8de62ab6bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzIyNTYsIm5iZiI6MTcxMzI3MTk1NiwicGF0aCI6Ii8xMzA5NTk4MzUvMzIyODQ1MDQ4LTk2MTQ1ZmZhLWY5MzktNDYxNS1hMTNmLTZiOGRlNjJhYjZiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMjUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzQ3MmFiNTkxNDZlNWJjODFlNTQ2ZWMxNWViNzQ1NDQyMjQ2NzQwNDQ4ZjE4YjFjMjVkMmNkZmVjOWIyYzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TNIGCJiQ3mtMRs7J2bJLnb743NlnSZuX3kaK9ilqwrk)
> > 还有，这是怎么分配IPV6的 ![AP1UV1JLX%XZ0CYFQ)0O6E8](https://private-user-images.githubusercontent.com/130959835/322845860-aec9a3d8-eec4-4b9e-bcb6-ee5d072751f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzIyNTYsIm5iZiI6MTcxMzI3MTk1NiwicGF0aCI6Ii8xMzA5NTk4MzUvMzIyODQ1ODYwLWFlYzlhM2Q4LWVlYzQtNGI5ZS1iY2I2LWVlNWQwNzI3NTFmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMjUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWMzYjg3ZWQyMmVkYTFkN2NlZDAwNTUwNjU3MTJiYmU0NGY2NzhjNzBhMGM2YzFiZTgxNDczMWY4NzQwNjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2xypipMYPE-n_qiNri48DYPNi9sOcSF0dzBN1JUrrgU)
> 
> 进容器查看`lsof -i:22` 还有，如果是新系统，推荐使用 https://github.com/oneclickvirt/incus

使用https://github.com/oneclickvirt/incus  获取不到系统镜像，我再试试lxd

**Comment by spiritLHLS** [comment]
> > > 在甲骨文amd安装后没有ssh，
> > > ![J3{NH5JFF0R{$4~5337CK4A](https://private-user-images.githubusercontent.com/130959835/322845048-96145ffa-f939-4615-a13f-6b8de62ab6bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzIyNTYsIm5iZiI6MTcxMzI3MTk1NiwicGF0aCI6Ii8xMzA5NTk4MzUvMzIyODQ1MDQ4LTk2MTQ1ZmZhLWY5MzktNDYxNS1hMTNmLTZiOGRlNjJhYjZiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMjUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzQ3MmFiNTkxNDZlNWJjODFlNTQ2ZWMxNWViNzQ1NDQyMjQ2NzQwNDQ4ZjE4YjFjMjVkMmNkZmVjOWIyYzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TNIGCJiQ3mtMRs7J2bJLnb743NlnSZuX3kaK9ilqwrk)
> > > 还有，这是怎么分配IPV6的 ![AP1UV1JLX%XZ0CYFQ)0O6E8](https://private-user-images.githubusercontent.com/130959835/322845860-aec9a3d8-eec4-4b9e-bcb6-ee5d072751f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzIyNTYsIm5iZiI6MTcxMzI3MTk1NiwicGF0aCI6Ii8xMzA5NTk4MzUvMzIyODQ1ODYwLWFlYzlhM2Q4LWVlYzQtNGI5ZS1iY2I2LWVlNWQwNzI3NTFmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMjUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWMzYjg3ZWQyMmVkYTFkN2NlZDAwNTUwNjU3MTJiYmU0NGY2NzhjNzBhMGM2YzFiZTgxNDczMWY4NzQwNjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2xypipMYPE-n_qiNri48DYPNi9sOcSF0dzBN1JUrrgU)
> > 
> > 
> > 进容器查看`lsof -i:22` 还有，如果是新系统，推荐使用 https://github.com/oneclickvirt/incus
> 
> 使用https://github.com/oneclickvirt/incus 获取不到系统镜像，我再试试lxd

获取不到就截图报错发对应issues，留言宿主机环境以及准备开设的容器的系统，我有空尝试复现BUG

**Comment by spiritLHLS** [comment]
> > 在甲骨文amd安装后没有ssh，
> > ![J3{NH5JFF0R{$4~5337CK4A](https://private-user-images.githubusercontent.com/130959835/322845048-96145ffa-f939-4615-a13f-6b8de62ab6bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzIyNTYsIm5iZiI6MTcxMzI3MTk1NiwicGF0aCI6Ii8xMzA5NTk4MzUvMzIyODQ1MDQ4LTk2MTQ1ZmZhLWY5MzktNDYxNS1hMTNmLTZiOGRlNjJhYjZiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMjUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzQ3MmFiNTkxNDZlNWJjODFlNTQ2ZWMxNWViNzQ1NDQyMjQ2NzQwNDQ4ZjE4YjFjMjVkMmNkZmVjOWIyYzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TNIGCJiQ3mtMRs7J2bJLnb743NlnSZuX3kaK9ilqwrk)
> > 还有，这是怎么分配IPV6的 ![AP1UV1JLX%XZ0CYFQ)0O6E8](https://private-user-images.githubusercontent.com/130959835/322845860-aec9a3d8-eec4-4b9e-bcb6-ee5d072751f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzIyNTYsIm5iZiI6MTcxMzI3MTk1NiwicGF0aCI6Ii8xMzA5NTk4MzUvMzIyODQ1ODYwLWFlYzlhM2Q4LWVlYzQtNGI5ZS1iY2I2LWVlNWQwNzI3NTFmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMjUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWMzYjg3ZWQyMmVkYTFkN2NlZDAwNTUwNjU3MTJiYmU0NGY2NzhjNzBhMGM2YzFiZTgxNDczMWY4NzQwNjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2xypipMYPE-n_qiNri48DYPNi9sOcSF0dzBN1JUrrgU)
> 
> 进容器查看`lsof -i:22` 还有，如果是新系统，推荐使用 https://github.com/oneclickvirt/incus

测试发现 lsof -i:22 是有占用的

![图片](https://github.com/oneclickvirt/lxd/assets/103393591/dcc53e1b-e6f5-484b-9668-58f787f2c803)

没发现问题，那个显示报错忽略即可
