### ISSUE TITLE
开设Alpine系统的容器，每次到这里都报错，开不了lxc容器

### ISSUE THREAD

**Issue by guan9527b** [spiritLHLS/lxc#31]
<img width="761" alt="image" src="https://github.com/oneclickvirt/lxd/assets/135665389/d99e4c56-f524-4e9f-a7c2-1121e5a1b4cf">

**Comment by spiritLHLS** [comment]
用的第三方新设立的源，可能存在任何bug，推荐使用

https://github.com/oneclickvirt/incus

**Comment by spiritLHLS** [comment]
![图片](https://github.com/oneclickvirt/lxd/assets/103393591/7b7e88e3-df51-4123-a271-7e2fb3cfe55e)

实测 alpine3.19 没问题，使用新系统即可

**Comment by spiritLHLS** [comment]
![图片](https://github.com/oneclickvirt/lxd/assets/103393591/bce3379c-cab0-4998-8adb-7c488cecfebb)

老实说3.16也没问题，大概率是你的宿主机的问题
