### ISSUE TITLE
一键脚本新建了一个小鸡ssh密码是多少

### ISSUE THREAD

**Issue by danielyi-code** [spiritLHLS/lxc#4]
如题

**Comment by spiritLHLS** [comment]
你可以看

https://github.com/spiritLHLS/lxc#%E6%9F%A5%E7%9C%8Blog%E6%96%87%E4%BB%B6

展开详细信息查看

或

https://github.com/spiritLHLS/lxc/blob/main/README.md#%E5%BC%80nat%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by danielyi-code** [comment]
谢谢🙏！
