### ISSUE TITLE
LXC小鸡如何与Ubuntu主机共享VPN

### ISSUE THREAD

**Issue by eomly** [spiritLHLS/lxc#6]
LXC小鸡如何使用宿主机的网络代理配置?

**Comment by spiritLHLS** [comment]
？我无法理解你的疑惑，LXC容器网络是高于母鸡设置的，自有一套网络拓扑

**Comment by eomly** [comment]
> ？我无法理解你的疑惑，LXC容器网络是高于母鸡设置的，自有一套网络拓扑

就是国内母鸡能实现科学上网，但是lxc小鸡不行。例如母鸡运行`wget www.google.com`可以下载index.html文件，但是lxc小鸡运行这个命令后无法下载。

**Comment by spiritLHLS** [comment]
额，本脚本制作时从未考虑国内母鸡的情况，你母鸡的全局代理是哪个层面的我都不知道，我无法给出任何建议，你如果需要小鸡内实现母鸡外的代理，那```lxd init```那里有个选项，问的是否将LXD网络权限高于宿主机网络权限，选择否，也许会有帮助

**Comment by eomly** [comment]
> 额，本脚本制作时从未考虑国内母鸡的情况，你母鸡的全局代理是哪个层面的我都不知道，我无法给出任何建议，你如果需要小鸡内实现母鸡外的代理，那`lxd init`那里有个选项，问的是否将LXD网络权限高于宿主机网络权限，选择否，也许会有帮助

好的，谢谢
