### ISSUE TITLE
开了小鸡ssh连不上

### ISSUE THREAD

**Issue by danielyi-code** [spiritLHLS/lxc#7]
curl -L https://github.com/spiritLHLS/lxc/raw/main/scripts/add_more.sh -o add_more.sh && chmod +x add_more.sh && bash add_more.sh
用的这个脚本
ssh显示connection refused
母鸡lxc可以内部连接，可能是NAT转发问题
端口检测后小鸡ssh端口关闭，其他端口正常

**Comment by spiritLHLS** [comment]
```
lsof -i:端口
```

看看输出，容器内外都看看，容器内看22，容器外看映射出来的外部SSH端口

**Comment by danielyi-code** [comment]
小鸡22端口sshd监听正常，母鸡lsof -i:20001无输出

**Comment by danielyi-code** [comment]
小鸡其他转发端口正常

**Comment by spiritLHLS** [comment]
> 小鸡22端口sshd监听正常，母鸡lsof -i:20001无输出

那就是没映射出去，你删掉该测试小鸡，重新创建，看看过程中有没有什么报错，感觉是网络映射出问题了，容器内部正常
