### ISSUE TITLE
提交新功能(增加自定义的内外网映射)

### ISSUE THREAD

**Issue by ghost** [spiritLHLS/lxc#8]
写了一个转发lxc容器内网端口的脚本项目地址
https://github.com/SevenSevenE/Lxc_nat

**Comment by spiritLHLS** [comment]
我的脚本使用

```
lxc config device add "$name" nattcp-ports proxy listen=tcp:0.0.0.0:$nat1-$nat2 connect=tcp:127.0.0.1:$nat1-$nat2
```

类似这样的命令作的端口映射，创建一个名为nattcp-ports的设备，并将它配置为进行端口映射，从而将容器的端口映射到主机的端口

你使用的iptables命令在Ubuntu22中无法使用，从Ubuntu20起，Ubuntu采用了netfilter的新规则引擎nftables，而不再使用iptables，而且如果重启服务器，映射没保存也会丢失，目前你的脚本有很多问题

综上，为什么不直接创建设备进行映射呢？

**Comment by ghost** [comment]
> 我的脚本使用
> 
> ```
> lxc config device add "$name" nattcp-ports proxy listen=tcp:0.0.0.0:$nat1-$nat2 connect=tcp:127.0.0.1:$nat1-$nat2
> ```
> 
> 类似这样的命令作的端口映射，创建一个名为nattcp-ports的设备，并将它配置为进行端口映射，从而将容器的端口映射到主机的端口
> 
> 你使用的iptables命令在Ubuntu22中无法使用，从Ubuntu20起，Ubuntu采用了netfilter的新规则引擎nftables，而不再使用iptables，而且如果重启服务器，映射没保存也会丢失，目前你的脚本有很多问题
> 
> 综上，为什么不直接创建设备进行映射呢？

我更新了脚本，因为宿主机一般都运行在ubuntu20.04系统上面，优化了脚本不会因为重启而丢失规则。我这种方法对于小白来说很方便只能说

**Comment by spiritLHLS** [comment]
> > 我的脚本使用
> > ```
> > lxc config device add "$name" nattcp-ports proxy listen=tcp:0.0.0.0:$nat1-$nat2 connect=tcp:127.0.0.1:$nat1-$nat2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 类似这样的命令作的端口映射，创建一个名为nattcp-ports的设备，并将它配置为进行端口映射，从而将容器的端口映射到主机的端口
> > 你使用的iptables命令在Ubuntu22中无法使用，从Ubuntu20起，Ubuntu采用了netfilter的新规则引擎nftables，而不再使用iptables，而且如果重启服务器，映射没保存也会丢失，目前你的脚本有很多问题
> > 综上，为什么不直接创建设备进行映射呢？
> 
> 我更新了脚本，因为宿主机一般都运行在ubuntu20.04系统上面，优化了脚本不会因为重启而丢失规则。我这种方法对于小白来说很方便只能说

唔，适配面不广，你自己用吧，暂时不考虑增加自定义的映射，这个功能得等我非常闲才能搓了:)
